ci: disable auto trigger on R type build
* there's a possibility where an endless  error loop creates
* if R type build fails then auto trigger script will start a system build to collect more ccache, and when that new build end it'll again start R type build
* now again R type build going to fail with same error which will end up starting another new system build like before
* this loop never going to end until we manually stop it
Signed-off-by: wHo-EM-i <ehteshammalik18998@gmail.com>

diff --git a/upload_ccache b/upload_ccache
--- a/upload_ccache
+++ b/upload_ccache
@@ -16,6 +16,20 @@ Time Took: $(($SECONDS / 60)) minute(s) and $(($SECONDS % 60)) second(s).
 Status: $progress | cache zip: $url"
 
 rom_zip=`ls /tmp/rom/out/target/product/*/*.zip`
+
+# Abort auto trigger on R build aka full rom
+# if it fails then its going to start new S type build which make no sense
+if [ -z $rom_zip ]; then # just to make sure build was failed or OOM kill happend
+check_build_type
+case "$build_type" in
+		 R|r)
+     # clean storage
+     rm -rf /tmp/rom
+     rm -rf /tmp/cache
+     exit 1
+esac
+fi
+
 if [ -z $rom_zip ]; then
 
 # update build type for next build
